### ISSUE TITLE
QuickFIX like configs

### ISSUE THREAD

**Issue by divaykin** [paritytrading/philadelphia#1]
what I like about QuickFIX is it's configuration model - one can do a lot with just changing session parameters to connect to a new venue. would be great to have something similar

**Comment by jvirtanen** [comment]
Sounds good! Can you elaborate a little on the strengths of QuickFIX/J? I have to admit that my experience with it is quite limited.

In Philadelphia, session configuration is set via the [`FIXConfig`](https://github.com/jvirtanen/philadelphia/blob/master/philadelphia/src/main/java/org/jvirtanen/philadelphia/FIXConfig.java) class. Custom fields and messages are also supported as Philadelphia, unlike most FIX engines, enforces neither field types nor message schemas. (See the [`FIXValue`](https://github.com/jvirtanen/philadelphia/blob/master/philadelphia/src/main/java/org/jvirtanen/philadelphia/FIXValue.java) and  [`FIXMessage`](https://github.com/jvirtanen/philadelphia/blob/master/philadelphia/src/main/java/org/jvirtanen/philadelphia/FIXMessage.java) classes for details.)

**Comment by divaykin** [comment]
http://www.quickfixj.org/quickfixj/usermanual/1.5.3/usage/configuration.html

see the example in the bottom. actually drop-in replacement of QuickFIX/J would be great in terms of configs.

what i like is
* you can set pretty much any standard header tag in the config
* default section is very useful, no need to repeat definitions
* you can set session storage parameters - location, etc
* you can set socket options used
* advanced features like failover hosts, etc

**Comment by sirinath** [comment]
@divaykin Wondering if you can contribute this in a very permanent way.

**Comment by jvirtanen** [comment]
In my mind I have classified features such as trading schedule, reconnection mechanism, and message persistence as well as message validation as _optional_. They are something that could definitely be built on top of Philadelphia, but I would keep them out of the library core.

Of course a Philadelphia-based drop-in replacement for QuickFIX/J would be great from a marketing perspective. :wink:

**Comment by jvirtanen** [comment]
Closing this, because at the moment it feels unlikely that Philadelphia could be used as a drop-in replacement for QuickFIX/J. (There were some attempts at that a few years ago.)
