### ISSUE TITLE
Incorrect outgoing seqno after sending `SequenceReset`

### ISSUE THREAD

**Issue by dm3** [paritytrading/philadelphia#231]
I've encountered the following sequence against FIX5.0SP1 server (O - outgoing from client, I - incoming):

  * `O 35=A|34=79|...` - Logon Request
  * `I 35=A|34=89|...` - Logon Response
  * `I 35=2|34=90|7=78|16=0|...` - Sequence Resend Request 78..Max
  * `O 35=4|34=78|123=Y|36=80|...` - Resend-GapFill 78..80
  * `O 35=D|34=81|...` - Next message, should be 34=80
  * `I 35=2|34=91|7=80|16=0|` - Resend Request as Server hasn't seen 34=80

According to [FIXT1.1](https://www.onixs.biz/fix-dictionary/fixt1.1/section_message_recovery.html) spec, this is a bug. Proposed fix: set `FIXConnection#txMsgSeqNum` to `newSeqNo` at the end of `FIXConnection#sendSequenceReset`. This way the next message will have the expected seqno.

Does this make sense?

**Comment by jvirtanen** [comment]
On a quick glance, looks like a good catch, @dm3! 🔍  I will check over the weekend that the earlier FIX protocol versions should work the same way, although I’m pretty sure that’s the case.

**Comment by jvirtanen** [comment]
@dm3 My apologies, this took a while. However, there's now a tentative patch available at #233. Note that it tries to handle also the situation in which the EndSeqNo(16) value is non-zero and smaller than the last MsgSeqNum(34) value.
