### ISSUE TITLE
Make Joda Time optional at runtime

### ISSUE THREAD

**Issue by ddimtirov** [paritytrading/philadelphia#235]
I am using Philadelphia Fix in a command line utility that I'm packaging as a GraalVM executable, and the Joda Time is a pet peeve of mine as it adds 2 MB to the total size of the executable,

I am proposing the following changes, and I would submit a PR if I get an indication that they are desirable.

**Background:**<br>
Looking at the use of Joda Time in Philadelphia codebase I see it is limited to `FIXTimestamps`, `FIXConnection` and `FIXValue`. From Joda time, we use `DateTimeZone`, `ReadableDateTime` and `MutableDateTime`,

**Proposal:**<br>
I would like to propose the following:

* In `FIXTimestamps`, add an overloaded `append()` method that accepts a `long` timestamp and formats it as UTC date.
* In `FIXConnection`, change the type of `currentTime` from `MutableDateTime` with `long`. This will also simplify `updateCurrentTimestamp()` and reduce copying (not that it matters that much).
* In `FIXValue`, add more getter and setter overloads using `long` timestamp 
  * Question: do we also wand JSR310 overloads? Convenient, but allocating garbage when we don't want it.

**Expected result:**<br>
* This will make the library interoperate better with our existing code, without having to convert to intermediate Joda Time representation.
* In the case of GraaVM NI, Gradle Shade relocation, minimization, etc. if the Joda time is not explicitly used, the code and dependency would be automatically removed.

**Comment by jvirtanen** [comment]
Hi @ddimtirov! This is a good point, and indeed, having a single third-party dependency has been bothering me as well.

Unfortunately I earlier only saw the title of this issue, and I already did a bit of prototyping based on that. (I had been thinking about making this change for quite some time, but there had been no discernible external demand for it until now.) My apologies if you had already some code written for this.

In essence, I came up with a mutable `FIXTimestamp` class that contains the fields that make up a FIX timestamp from the year to the millisecond. The methods on `FIXValue` that currently take a `MutableDateTime` or a `ReadableDateTime` now take a `FIXTimestamp` instead.

In addition, `FIXTimestamp` contains methods to get and set its value as milliseconds. Those are implemented using [`Calendar`](https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.html) and generate no garbage.

As I see, this should be the best of the both worlds: like [`java.time`](https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html) a.k.a. JSR 310, `FIXTimestamp` provides no cost access to the constituent fields and only bears the cost if the aforementioned conversion methods to and from milliseconds are used. On the other hand, like [`MutableDateTime`](https://www.joda.org/joda-time/apidocs/org/joda/time/MutableDateTime.html), `FIXTimestamp` is mutable and generates no garbage.

Initial microbenchmarks look positive: parsing and formatting a `FIXTimestamp` value is much faster than a `ReadableDateTime` or a `MutableDateTime` value. Even when a conversion to or from milliseconds is included, the performance looks better than with Joda-Time currently.

How does this sound to you?

**Comment by ddimtirov** [comment]
Sounds great, do you need any help or testing?

The code we already have is localized and easy to update.

**Comment by jvirtanen** [comment]
I'll notify on this issue when I post a pull request, a code review will be very welcome. 👍🏼

**Comment by jvirtanen** [comment]
I just opened #237.

**Comment by jvirtanen** [comment]
Closed by #237.
