### ISSUE TITLE
String representation of FIXSession

### ISSUE THREAD

**Issue by jheusser** [paritytrading/philadelphia#26]
If you have multiple `FIXSession` instances active it would be useful to be able to distinguish them on the callbacks to `FIXStatusListener`. Either giving `FIXSession` a `toString` representation or perhaps exposing parts of its `FIXConfig` (e.g. `SenderCompId`).

**Comment by jvirtanen** [comment]
Yes, this is a good point. Perhaps simplest would be to add `getSenderCompID` and `getTargetCompID` methods as you suggest.

In the same vein, the existing `getChannel` method can be used to access the underlying socket channel instance. Through it you can get the remote IP address and TCP port, for example.

**Comment by jvirtanen** [comment]
@jheusser My apologies, I have been quite busy recently. Would you be interested in contributing a patch for this yourself? Alternatively I can have a look at this a bit later.

**Comment by jheusser** [comment]
@jvirtanen No problem, your suggestion of getting the channel via `getChannel` is good, as it has a nice string representation. But in general adding a `getSenderCompID` and `getTargetCompID` should be useful, I can submit a PR later on for that?

**Comment by jvirtanen** [comment]
@jheusser Yes, I think it would be good to add `getSenderCompID` and `getTargetCompID` as well.
