### ISSUE TITLE
Expose rxMsgSeqNum and txMsgSeqNum

### ISSUE THREAD

**Issue by jheusser** [paritytrading/philadelphia#27]
Ability to access current `rxMsgSeqNum` and `txMsgSeqNum` on a `FIXSession`. There's a package private method `getInboundMsgSeqNum`, perhaps the same for outbound and both public? Access is necessary to persist sequence numbers in case of logon without sequence reset and a `FIXSession` is instantiated with specific sequence numbers.

**Comment by jvirtanen** [comment]
Yes, this is a needed addition.

I noticed that currently the API uses "inbound" and "incoming" as well as "outbound" and "outgoing" interchangeably. The API should settle on either of them. I have to check what is the terminology used in the protocol specification.

**Comment by jheusser** [comment]
Yes, currently `FIXSession` is using inbound/incoming/rx and outbound/outgoing/tx.

**Comment by jvirtanen** [comment]
Perhaps "incoming" and "outgoing" are better as they are already used on `FIXConfig` whereas `getInboundMsgSeqNum` on `FIXSession` is only part of the private interface.
