### ISSUE TITLE
Can we add support FIX 4.0 and 4.1?

### ISSUE THREAD

**Issue by ddimtirov** [paritytrading/philadelphia#287]
I am hitting an issue where my client needs to establish a (heavily bastardized) 4.0 connection, and my current tool does not support it because `FIXVersions` is an enum and does not provide the right constant.

A more general solution would be to introduce an interface `FixStartStringProvider` and have the `FIXVersions` enum implement that. This way people's code will keep working as before (source and binary compatible), and I can specify a funky start string when I need it.

Let me know if you'd like a PR.

@jvirtanen

**Comment by jvirtanen** [comment]
FIX 4.0 and FIX 4.1 have not been supported because there hasn't been demand for them in the past. Now that there is, it certainly makes sense to add them. #288 introduces FIX 4.0 support for starters.

**Comment by ddimtirov** [comment]
Thanks, I had a look and it is more and at the same time less than what I need. I am pretty sure that the guys also need FIX 4.1 too (I'll check next week). At the same time we don't need a Java dictionary.

Being able to specify a start string would solve this and all future needs for this application. We would also need a dictionary at some point, for validation but then the generated classes would not be enough as they are missing the message schema.

**Comment by jvirtanen** [comment]
#289 introduced FIX 4.1 support, and #294 made it possible to set an arbitrary BeginString(8) value in `FIXConfig`.
