### ISSUE TITLE
Proper initialization of lastTxMillis and lastRxMillis required

### ISSUE THREAD

**Issue by dmech** [paritytrading/philadelphia#301]
`lastTxMillis` and `lastRxMillis` in [FIXConnection](https://github.com/paritytrading/philadelphia/blob/765c1c5123d761aa411c32e03e7d186ccdec98fc/libraries/core/src/main/java/com/paritytrading/philadelphia/FIXConnection.java) are both initialized with 0.

If `Keepalive()` is called before any data reception or transmission, e.g. in the [Receiver of the sample application](https://github.com/paritytrading/philadelphia/blob/765c1c5123d761aa411c32e03e7d186ccdec98fc/applications/client/src/main/java/com/paritytrading/philadelphia/client/Session.java), `Keepalive()` triggers a `sendHeartbeat()` and a `sendTestRequest()`.

No other message than a Logon message should be the first message after a connect.

My quickfix is an initialization of `lastTxMillis` and `lastRxMillis` with `System.currentTimeMillis()` so `sendHeartbeat()` and a `sendTestRequest()` are not immediatly triggered after a connect.

**Comment by jvirtanen** [comment]
Hi @dmech! That's a valid point, and this looks to be a regression in b527f7b5230ddf5a44086710ba62b7b23c62f0e2. Would you like to open a pull request to fix this? It would be nice to add a test case for this too.

**Comment by dmech** [comment]
Sure, I am on it.
