### ISSUE TITLE
FIXSession can't be inherited from

### ISSUE THREAD

**Issue by jheusser** [paritytrading/philadelphia#31]
Not sure if a `FIXSession` is supposed to be inheritable, but if it is then it's currently not possible as `Clock` and `SystemClock` are not publicly visible.

**Comment by jvirtanen** [comment]
The class is indeed not designed with inheritance in mind. What kind of functionality are you building on top of it? Perhaps we can find another, more idiomatic way to accomplish that.

**Comment by jheusser** [comment]
Actually I was more just experimenting, not a very concrete reason just yet. Good to know it's not designed for inheritance.

**Comment by jvirtanen** [comment]
In principle, all Parity projects consist of interfaces that are meant to be implemented and classes that by default are not designed inheritance in mind. I will add a reminder to mention this in the [Parity Guide](https://github.com/paritytrading/documentation).

**Comment by penberg** [comment]
@jvirtanen So make the `FIXSession` class definition `final`. That's a pretty good hint to readers that the class is not designed for inheritance :wink:
