### ISSUE TITLE
FIX44Enumerations.CxlRejResponseToValues

### ISSUE THREAD

**Issue by jheusser** [paritytrading/philadelphia#32]
Value '2' should be called OrderCancelReplaceRequest

http://www.onixs.biz/fix-dictionary/4.4/tagNum_434.html

**Comment by penberg** [comment]
The same applies to all FIX versions, btw.

**Comment by jvirtanen** [comment]
I agree that it is confusing.

The enumerations are generated based on the [FIX Repository](http://www.fixtradingcommunity.org/pg/structure/tech-specs/fix-tools/fix-repository), which specifies a description and a symbolic name for each value. For CxlRejResponseTo(434), the value 2 has the description "Order Cancel/Replace Request" and, for some reason, the symbolic name `OrderCancel`.

Any thoughts on this?

**Comment by jheusser** [comment]
I think "Order Cancel/Replace Request" means "Order Cancel Replace Request" 😄 

In our use case value '2' is only used on a order cancel reject originating from an order cancel replace request.

**Comment by jvirtanen** [comment]
Yes, indeed. The values in the FIX Repository are as follows:

Value | Symbolic Name | Description
------|----------------|-------------
1        | `OrderCancelRequest` | Order Cancel Request
2       | `OrderCancel` | Order Cancel/Replace Request

So I'm kind of blaming the FIX Repository here. (Maybe _they_ generate the symbolic names from the descriptions, and their generator breaks down at the slash).

**Comment by jheusser** [comment]
Cool ok makes sense in this case if it agrees with the FIX repo, even though I also think the slash tripped the generator up 💣

**Comment by jvirtanen** [comment]
Maybe Philadelphia's code generator could generate an `OrderCancelReplaceRequest` alias here...
