### ISSUE TITLE
Make checksum in `FIXMessageParser` optional

### ISSUE THREAD

**Issue by jheusser** [paritytrading/philadelphia#37]
It would be a nice feature to make the `FIXCheckSums.sum` branch optional in `FIXMessageParser`.

Also related to that, if that change was made, it would be nice to add a `FIXMessageParser` perf-test, but for that the class would need to be public.

**Comment by jvirtanen** [comment]
That's a good idea, thanks! :+1:

Yes, a performance test for `FIXMessageParser` would be good to add. I see no reason not make the class public, although it would be of fairly limited utility. Perhaps it would be a better idea to move the performance tests to the same package as the classes under test.

**Comment by jheusser** [comment]
Actually would also include the other branches touching `checkSum` field I assume.

**Comment by jvirtanen** [comment]
@jheusser Yes, makes sense. I'll look into this on the starting week.

**Comment by jvirtanen** [comment]
@jheusser I just pushed the changes that make the incoming CheckSum(10) check optional. I'll add a performance test for `FIXMessageParser` a bit later.

**Comment by jheusser** [comment]
Great, thanks 👍
