### ISSUE TITLE
Expose constructor in FIXSession

### ISSUE THREAD

**Issue by jheusser** [paritytrading/philadelphia#53]
It would be nice if the constructor would be public in `FIXSession` to pass in external clock:
```
FIXSession(Clock clock, SocketChannel channel, FIXConfig config, FIXMessageListener listener, FIXStatusListener statusListener)
```

**Comment by jvirtanen** [comment]
Yes, good idea. :+1:

**Comment by jheusser** [comment]
Also related to that, the class `SystemClock` is probably superfluous and can be replaced with `System::currentTimeMillis` usage these days.

**Comment by jvirtanen** [comment]
Yes, definitely. That is a remnant from the Java 7 times. 🙂
